backend:
  name: github
  repo: y-sashikata/test   
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "nav"
    label: "ヘッダーメニュー"
    folder: "content/nav"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - { label: "ラベル", name: "label", widget: "string" }
      - { label: "リンク先", name: "to", widget: "string", required: false }
      - { label: "並び順", name: "order", widget: "number", default: 0 }
      - name: "children"
        label: "子メニュー"
        widget: "list"
        required: false
        fields:
          - { label: "ラベル", name: "label", widget: "string" }
          - { label: "リンク先", name: "to", widget: "string" }
          - { label: "並び順", name: "order", widget: "number", default: 0 }
          - name: "children"
            label: "孫メニュー"
            widget: "list"
            required: false
            fields:
              - { label: "ラベル", name: "label", widget: "string" }
              - { label: "リンク先", name: "to", widget: "string" }
              - { label: "並び順", name: "order", widget: "number", default: 0 }
  - name: "news"
    label: "お知らせ"
    folder: "content/news"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "固定ページ"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "パス", name: "path", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
