backend:
  name: git-gateway  
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "お知らせ"
    folder: "content/news"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }

  - name: "pages"
    label: "固定ページ"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "パス", name: "path", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
